language: cpp

dist: focal

compiler:
          - gcc

before_install:
          - sudo apt update -qq
          - wget https://github.com/robotology/yarp/releases/download/v3.3.2/yarp-3.3.2-2.focal_amd64.deb
install:
          - sudo apt install -qq cmake build-essential libopencv-dev libace-dev libeigen3-dev yarp-3.3.2-2.focal_amd64.deb

before_script:
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$MYDIR/yarp/build -DBUILD_APPLICATIONS=ON -DBUILD_HARDWAREIO=ON -DBUILD_PROCESSING=ON -DENABLE_autosaccade=ON -DENABLE_binarydumper=ON -DENABLE_calibrate=ON -DENABLE_corner=ON -DENABLE_vCluster=ON -DENABLE_vFramer=ON -DENABLE_vPreProcess=ON -DENABLE_vSkinInterface=ON -DENABLE_view=ON -DENABLE_zynqgrabber=ON

script: make -j 2
